-----------------------------------
-- XI_LIFE: PlayerNPC city population
--
-- Populates every city zone a player walks into with dynamic NPCs that look and move like other
-- players: they arrive somewhere, loiter, walk on, and eventually leave through a zone line or a
-- home point crystal.
--
-- Hooks in through InteractionGlobal rather than per-zone scripts. luautils calls
-- InteractionGlobal.afterZoneIn and InteractionGlobal.onZoneOut unconditionally for every zone,
-- passing the zone's own handler in as a fallback, so overriding those two reaches all 250-odd
-- zones without editing a single Zone.lua.
--
-- Points of interest come from modules/custom/lua/xi_life_pois.lua, which is generated by
-- tools/xi_life/generate_pois.py out of npc_list, zonelines and the zone scripts.
-----------------------------------
require('modules/module_utils')
require('scripts/globals/interaction/interaction_global')
require('modules/custom/lua/xi_life_appearance')
require('modules/custom/lua/xi_life_pois')
require('modules/custom/lua/xi_life_chatter')

-- Hand-picked points added in game with !addnpcpoi. Optional: the file only exists once the
-- command has been used at least once, so this must not be a hard require. pcall rather than
-- utils.prequire, which lives in scripts/utils and may not be loaded this early.
pcall(require, 'modules/custom/lua/xi_life_custom_pois')
-----------------------------------
local m = Module:new('xi_life')

-----------------------------------
-- Tuning
-----------------------------------

-- How long a freshly spawned PNPC stands before setting off.
local ARRIVAL_PAUSE_MS = 8000

-- Loitering. Auction counters get longer: players genuinely stand at them a while, working the
-- menu and re-listing. Home points are a shorter pause for the ones who do not warp straight out.
local AUCTION_LOITER_MS   = 30000
local HOMEPOINT_LOITER_MS = 15000
local WANDER_LOITER_MS    = 15000

-- Chance a PNPC arriving at a home point warps out rather than loitering and moving on. Mostly
-- terminal, since that is what a player at a crystal is usually doing. The quarter that stay are
-- what keeps the eleven city zones with no auction house from being silent thoroughfares - a home
-- point is their only loiter point.
local HOMEPOINT_DEPARTURE_CHANCE = 75

-- A PNPC warping out stands at the crystal a moment first. Arriving and vanishing on the same step
-- reads as a despawn bug; a beat of stillness reads as someone casting the warp. Spread over a
-- couple of seconds so a pair arriving together do not blink out on the same frame.
local HOMEPOINT_WARP_MIN_MS = 3000
local HOMEPOINT_WARP_MAX_MS = 5000

-- Gap between one PNPC leaving and its replacement arriving.
local RESPAWN_DELAY_MS = 3000

-- Stagger the initial fill so a city does not pop into existence all at once.
local SPAWN_STAGGER_MS = 1000

-- Chatter. The budget is per zone rather than per PNPC: twenty people each on their own timer is
-- a spam wall, and the rate would change every time the population did. One speaker is picked
-- from whoever is alive when the timer fires, so the pace stays constant in a hamlet or a capital.
local CHATTER_MIN_DELAY_MS = 10000
local CHATTER_MAX_DELAY_MS = 45000

-- 'say' lines are muttering, so they only carry if the speaker is close enough to overhear.
local SAY_RANGE = 20.0

-- Yalms of slop on x and z, used only when a point has no standing slot free. y is left alone:
-- nudging it risks putting someone through the floor or off a ledge.
local DEST_JITTER = 1.5

-- Standing slots. A PNPC does not walk onto the thing it came to see - it claims a spot on a ring
-- around it, holds that spot against everyone else, and turns to face the middle. Radius is per
-- kind because the objects differ in size: a home point crystal is a good deal wider than the
-- counter clerk you queue in front of.
local SLOT_COUNT = 8

local slotRadius =
{
    auction   = 2.0,
    homepoint = 2.0,
    wander    = 2.0,
}

local DEFAULT_SLOT_RADIUS = 2.2

-- Stuck rescue. A PNPC that stops making progress never reaches onPathComplete, so nothing in the
-- normal lifecycle can recover it - it stands there for the rest of the session. Watch for the
-- symptom instead of trusting that every destination is reachable: consecutive ticks with no
-- meaningful movement while still nominally following a path.
local STUCK_MOVE_EPSILON = 0.5
local STUCK_STRIKES      = 3

-- Points approachable from any angle. Everything else is up against something - a counter has a
-- wall behind it, a shopkeeper has their stall - so a PNPC should only ever stop on the side it
-- came in from. The navmesh already rules out most of the bad arc (see buildSlots), but it cannot
-- know that walking around to the one free spot behind the counter looks absurd even where the
-- floor is technically walkable.
local fullCircleKinds =
{
    homepoint = true,
}

-- Roadside encounters. Two PNPCs travelling past each other may stop, turn, and stand talking for
-- a few seconds before carrying on. Capped at one per trip each, so the same pair cannot bounce
-- off each other all the way across a city.
-- The range is a band, not a radius. Below the near edge the two are close enough to be clipping
-- through each other, which is not a conversation; beyond the far edge they are shouting across
-- the street. They stop where they stand when the roll lands, so the band is the gap they end up
-- talking across.
local ENCOUNTER_TICK_MS  = 2500
local ENCOUNTER_NEAR     = 2.0
local ENCOUNTER_FAR      = 5.0
local ENCOUNTER_HEIGHT   = 3.0
local ENCOUNTER_CHANCE   = 12
local ENCOUNTER_MIN_MS   = 5000
local ENCOUNTER_MAX_MS   = 9000

-- Resuming after an encounter needs somewhere left to walk to. PathTo refuses a destination within
-- a yalm, so a PNPC stopped almost on top of its slot is treated as having arrived instead.
local RESUME_MIN_DISTANCE = 2.0

-- A zone needs somewhere to go and somewhere to leave from, or its PNPCs have nothing to do.
local MIN_POINTS      = 2
local MIN_EXIT_POINTS = 1

-- CPathFind::PathTo silently does nothing when the destination is within 1 yalm of where the
-- entity already stands (arePositionsClose in pathfind.cpp), which would leave a PNPC parked
-- forever with no onPathComplete to move it on. Keep destinations comfortably clear of that.
local MIN_TRAVEL_DISTANCE = 5.0

-- Kinds a PNPC stops travelling at. Everything else is somewhere it passes through.
local terminalKinds =
{
    exit      = true,
    homepoint = true,
}

-- Zones whose content may not be enabled on this server. Nothing else needs gating: the rest of
-- the generated zones are base game.
local zoneContentTag =
{
    [xi.zone.TAVNAZIAN_SAFEHOLD]     = 'COP',
    [xi.zone.AL_ZAHBI]               = 'TOAU',
    [xi.zone.AHT_URHGAN_WHITEGATE]   = 'TOAU',
    [xi.zone.SOUTHERN_SAN_DORIA_S]   = 'WOTG',
    [xi.zone.BASTOK_MARKETS_S]       = 'WOTG',
    [xi.zone.WINDURST_WATERS_S]      = 'WOTG',
    [xi.zone.WESTERN_ADOULIN]        = 'SOA',
    [xi.zone.EASTERN_ADOULIN]        = 'SOA',
}

-----------------------------------
-- State
--
-- One entry per zone we have looked at. `points` is the navmesh-validated subset of the generated
-- data, `live` counts PNPCs currently walking around, and `active` says whether a player is here
-- to see them.
-----------------------------------

local zoneState = {}

-- Local vars are integers, so a PNPC's job is stored as its index into the chatter job list.
local jobIndex = {}
for index, job in ipairs(xi.xiLife.chatter.tokens.job) do
    jobIndex[job] = index
end

local function jitter(value)
    return value + ((math.random() * 2) - 1) * DEST_JITTER
end

-- Players who can actually see the city. Entering a Mog House does not change zone - it is a zone
-- change to the same zone (0x05e_maprect.cpp), leaving the player standing at their city position
-- as far as the server is concerned while the client draws a room around them. Such a player is
-- not an audience for any of this, and must not anchor the zone's timers either.
local function watchingPlayers(zone)
    local found = {}

    for _, player in pairs(zone:getPlayers()) do
        if not player:inMogHouse() then
            table.insert(found, player)
        end
    end

    return found
end

local function anyPlayerIn(zone)
    return watchingPlayers(zone)[1]
end

-----------------------------------
-- Standing slots
--
-- Every point of interest that is not a way out gets a ring of standing positions around it, worked
-- out once when the zone is prepared. A PNPC heading for a point claims one for the whole journey,
-- so two of them can never pick the same spot even while both are still walking, and on arrival it
-- turns to face the middle of the ring - which is the thing it came to see.
-----------------------------------

-- The ring is filtered against the navmesh, which does most of the work for free. isNavigablePoint
-- searches with a 0.5 yalm horizontal extent (smallPolyPickExt in navmesh.cpp), tight enough to
-- tell one side of an auction counter from the other: the counter geometry is baked into the mesh,
-- so the slots behind it fail and the arc carves itself out without anyone hand-measuring a zone.
local function buildSlots(zone, point)
    if point.kind == 'exit' then
        return {}
    end

    local radius  = slotRadius[point.kind] or DEFAULT_SLOT_RADIUS
    local floorId = zone:getFloorId({ x = point.x, y = point.y, z = point.z })
    local slots   = {}

    for i = 0, SLOT_COUNT - 1 do
        local angle = (i / SLOT_COUNT) * 2 * math.pi
        local x     = point.x + (math.cos(angle) * radius)
        local z     = point.z + (math.sin(angle) * radius)
        local probe = { x = x, y = point.y, z = z }

        -- Two tests, because isNavigablePoint alone is not enough. It answers with a 1 yalm
        -- vertical pick extent, but pathTo routes with a 5 yalm one (polyPickExt in navmesh.cpp),
        -- so a slot can validate against the ground and then have its route snapped to a storey
        -- above. Lower Jeuno's auction house has a walkway directly over the counters and did
        -- exactly that. getFloorId asks the zone mesh which storey a position belongs to - the
        -- same question WideScan asks to decide what a player can see - so requiring a match
        -- rejects a slot whose only surface is upstairs.
        local usable =
            zone:isNavigablePoint(probe) and
            zone:getFloorId(probe) == floorId

        if usable then
            table.insert(slots, { x = x, z = z })
        end
    end

    return slots
end

-- Pick a free slot, preferring the half of the ring the PNPC is coming in from. Jogging around
-- behind a stall to stand in the one free spot reads as a bug; stopping on the near side reads as
-- joining the queue. fromX nil means there is no approach to speak of - a PNPC being spawned in -
-- so the whole ring is fair game, as it is for the kinds listed in fullCircleKinds.
--
-- Returns 0 when nothing is free, which is the caller's cue to fall back to a jittered arrival at
-- the point itself. A busy auction house should still look busy.
local function chooseSlot(point, fromX, fromZ)
    local anyAngle = fullCircleKinds[point.kind] or fromX == nil
    local nearSide = {}
    local anySide  = {}

    -- Vector from the point out towards wherever the PNPC currently is. A slot on the approach side
    -- has a positive dot product with it, which is just 'within 90 degrees of the way they came'.
    local approachX = (fromX or 0) - point.x
    local approachZ = (fromZ or 0) - point.z

    for idx, slot in ipairs(point.slots) do
        if not point.taken[idx] and not slot.bad then
            table.insert(anySide, idx)

            local dot = ((slot.x - point.x) * approachX) + ((slot.z - point.z) * approachZ)
            if dot > 0 then
                table.insert(nearSide, idx)
            end
        end
    end

    if anyAngle then
        if #anySide == 0 then
            return 0
        end

        return anySide[math.random(#anySide)]
    end

    if #nearSide == 0 then
        return 0
    end

    return nearSide[math.random(#nearSide)]
end

-- Give up the slot a PNPC holds, if it still holds it. The id check matters: a slot released twice
-- must not evict whoever claimed it in between.
local function releaseSlot(state, npc)
    local point   = state and state.points[npc:getLocalVar('xiLifePoint')]
    local slotIdx = npc:getLocalVar('xiLifeSlot')

    if point and slotIdx > 0 and point.taken[slotIdx] == npc:getID() then
        point.taken[slotIdx] = nil
    end

    npc:setLocalVar('xiLifeSlot', 0)
end

-- Where a PNPC holding this slot should actually stand. Slot positions are fixed, so this can be
-- recomputed from the two local vars alone and survives an interrupted journey.
local function destinationOf(point, slotIdx)
    local slot = slotIdx > 0 and point.slots[slotIdx]
    if slot then
        return slot.x, point.y, slot.z
    end

    return jitter(point.x), point.y, jitter(point.z)
end

-----------------------------------
-- Zone preparation
--
-- Run once per zone, the first time a player arrives. The generator cannot consult the navmesh -
-- it lives in this process, not in Python - so the points it produces are candidates, and this is
-- where the unreachable ones are dropped. A PNPC sent to an off-mesh point would stall short of
-- it, never arriving and so never despawning.
-----------------------------------

local function prepareZone(zone, zoneId)
    if zoneState[zoneId] then
        return zoneState[zoneId]
    end

    local data = xi.xiLife.pois[zoneId]
    if not data then
        zoneState[zoneId] = { enabled = false }

        return zoneState[zoneId]
    end

    local contentTag = zoneContentTag[zoneId]
    if contentTag and not xi.module.isContentEnabled(contentTag) then
        zoneState[zoneId] = { enabled = false }

        return zoneState[zoneId]
    end

    local candidates = {}
    for _, point in ipairs(data.points) do
        table.insert(candidates, point)
    end

    -- Points added in game with !addnpcpoi, layered on top of the generated set. They survive
    -- regeneration because they live in their own file.
    local custom = xi.xiLife.customPois and xi.xiLife.customPois[zoneId]
    if custom then
        for _, point in ipairs(custom) do
            table.insert(candidates, point)
        end
    end

    local points   = {}
    local rejected = 0

    for _, point in ipairs(candidates) do
        -- Zone lines are never culled. They are the only way out of a zone, and losing them
        -- strands the whole population. They also do not need the mesh: PathTo is called with
        -- WALLHACK, which routes through CPathFind::FindClosestPath, and that appends the exact
        -- destination to the path regardless of what the navmesh says. The NPC walks the mesh as
        -- far as it goes and then moves directly to the point, so arrival still happens.
        local keep =
            point.kind == 'exit' or
            zone:isNavigablePoint({ x = point.x, y = point.y, z = point.z })

        if keep then
            -- Copy rather than reference: the generated table is module-level shared data, and the
            -- runtime hangs per-zone slot occupancy off these entries.
            table.insert(points,
            {
                name  = point.name,
                kind  = point.kind,
                x     = point.x,
                y     = point.y,
                z     = point.z,
                slots = buildSlots(zone, point),
                taken = {},
            })
        else
            rejected = rejected + 1
            printf('[XI_LIFE] %s: point off the navmesh, dropped: %s (%s)',
                zone:getName(), point.name, point.kind)
        end
    end

    local exits = 0
    for _, point in ipairs(points) do
        if terminalKinds[point.kind] then
            exits = exits + 1
        end
    end

    local enabled = #points >= MIN_POINTS and exits >= MIN_EXIT_POINTS

    zoneState[zoneId] =
    {
        enabled    = enabled,
        points     = points,
        population = data.population,
        live       = 0,
        active     = false,
        watch      = {},
    }

    local slotCount = 0
    for _, point in ipairs(points) do
        slotCount = slotCount + #point.slots
    end

    if enabled then
        printf('[XI_LIFE] %s: %d points (%d dropped), %d standing slots, population %d',
            zone:getName(), #points, rejected, slotCount, data.population)
    else
        printf('[XI_LIFE] %s: disabled, only %d usable points and %d ways to leave',
            zone:getName(), #points, exits)
    end

    return zoneState[zoneId]
end

-----------------------------------
-- PlayerNPC lifecycle
-----------------------------------

local spawnOne
local walkToRandomPoint
local arriveAt
local leave

-- Sends the PNPC somewhere it is not already standing, and remembers which point it chose so
-- onPathComplete knows what kind of place it just arrived at.
--
-- Two candidates are refused. Walking from one auction counter to another looks absurd - the
-- counters share a room, so it reads as pacing rather than travelling. And anything within
-- MIN_TRAVEL_DISTANCE would leave the NPC stranded, since PathTo ignores destinations that close.
-- If nothing at all qualifies the PNPC leaves rather than standing there indefinitely, since
-- without a path there is no onPathComplete to ever move it on again.
walkToRandomPoint = function(npc, zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled then
        return
    end

    if not state.active then
        leave(npc, zone, zoneId)

        return
    end

    local currentIdx   = npc:getLocalVar('xiLifePoint')
    local currentPoint = state.points[currentIdx]
    local atAuction    = currentPoint and currentPoint.kind == 'auction'

    local preferred = {}
    local fallback  = {}

    for idx, point in ipairs(state.points) do
        if idx ~= currentIdx then
            local dx        = point.x - npc:getXPos()
            local dz        = point.z - npc:getZPos()
            local farEnough = ((dx * dx) + (dz * dz)) > (MIN_TRAVEL_DISTANCE * MIN_TRAVEL_DISTANCE)

            if farEnough then
                if atAuction and point.kind == 'auction' then
                    table.insert(fallback, idx)
                else
                    table.insert(preferred, idx)
                end
            end
        end
    end

    local choices = #preferred > 0 and preferred or fallback
    if #choices == 0 then
        leave(npc, zone, zoneId)

        return
    end

    local destIdx     = choices[math.random(#choices)]
    local destination = state.points[destIdx]

    -- Give up the spot they have been standing in before claiming the next, or a PNPC crossing the
    -- city would hold two slots for the length of the walk.
    releaseSlot(state, npc)

    local slotIdx = chooseSlot(destination, npc:getXPos(), npc:getZPos())
    if slotIdx > 0 then
        destination.taken[slotIdx] = npc:getID()
    end

    npc:setLocalVar('xiLifePoint', destIdx)
    npc:setLocalVar('xiLifeSlot', slotIdx)

    -- One roadside encounter per trip, so a pair heading the same way cannot keep stopping.
    npc:setLocalVar('xiLifeMet', 0)

    local x, y, z = destinationOf(destination, slotIdx)

    npc:pathTo(x, y, z, xi.path.flag.WALLHACK + xi.path.flag.SCRIPT)
end

local function scheduleReplacement(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active or state.live >= state.population then
        return
    end

    local player = anyPlayerIn(zone)
    if not player then
        return
    end

    player:timer(RESPAWN_DELAY_MS, function(_)
        spawnOne(zone, zoneId)
    end)
end

leave = function(npc, zone, zoneId)
    local state = zoneState[zoneId]

    releaseSlot(state, npc)
    npc:setStatus(xi.status.DISAPPEAR)

    if state then
        state.live = math.max(0, state.live - 1)
    end

    scheduleReplacement(zone, zoneId)
end

-- What happens when a PNPC reaches the place it was walking to. Lifted out of the onPathComplete
-- closure because a trip can also end without the path completing: a PNPC that stopped for a
-- roadside encounter almost on top of its slot has nowhere left to walk, and arrives from here
-- instead.
arriveAt = function(npc, zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active then
        leave(npc, zone, zoneId)

        return
    end

    local arrived = state.points[npc:getLocalVar('xiLifePoint')]
    local kind    = arrived and arrived.kind or 'exit'

    -- Turn and face whatever they came to see - the counter clerk, the crystal, the shopkeeper.
    -- Exits are the exception: a zone line is a doorway rather than a destination, and the PNPC
    -- despawns on reaching one anyway. lookAt sets UPDATE_POS, which is the safe way to move a
    -- dynamic NPC's rotation; it is a no-op if they somehow ended up on top of the point.
    if arrived and kind ~= 'exit' then
        npc:lookAt(arrived.x, arrived.y, arrived.z)
    end

    if kind == 'auction' then
        npc:timer(AUCTION_LOITER_MS, function(n)
            walkToRandomPoint(n, zone, zoneId)
        end)

        return
    end

    -- Points added in game with !addnpcpoi. Somewhere to stand, never a way out.
    if kind == 'wander' then
        npc:timer(WANDER_LOITER_MS, function(n)
            walkToRandomPoint(n, zone, zoneId)
        end)

        return
    end

    -- Home points are both a place to stand and a way out, so roll for which this is.
    if kind == 'homepoint' then
        if math.random(100) > HOMEPOINT_DEPARTURE_CHANCE then
            npc:timer(HOMEPOINT_LOITER_MS, function(n)
                walkToRandomPoint(n, zone, zoneId)
            end)

            return
        end

        npc:timer(math.random(HOMEPOINT_WARP_MIN_MS, HOMEPOINT_WARP_MAX_MS), function(n)
            leave(n, zone, zoneId)
        end)

        return
    end

    -- Zone lines, which are the only other way out. These do vanish on contact: that is exactly
    -- what walking through a zone line looks like from the outside.
    leave(npc, zone, zoneId)
end

spawnOne = function(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled or not state.active then
        return
    end

    if state.live >= state.population then
        return
    end

    local startIdx   = math.random(#state.points)
    local startPoint = state.points[startIdx]
    local character  = xi.xiLife.appearance.randomCharacter()

    -- No approach direction to speak of for someone being placed rather than arriving, so the whole
    -- ring is eligible. The slot is only marked taken once the entity exists and has an id, a few
    -- lines down - nothing can run in between to steal it.
    local startSlot = chooseSlot(startPoint, nil, nil)
    local x, y, z   = destinationOf(startPoint, startSlot)

    local npc = zone:insertDynamicEntity(
    {
        objtype  = xi.objType.NPC,
        name     = character.name,
        look     = character.look,
        x        = x,
        y        = y,
        z        = z,
        rotation = math.random(0, 255),

        -- namevis 0, not VIS_ICON: the (I) icon marks a talkable NPC and gives the game away.
        namevis  = 0,
        releaseIdOnDisappear = true,

        onPathComplete = function(pnpc)
            arriveAt(pnpc, zone, zoneId)
        end,
    })

    if not npc then
        return
    end

    state.live = state.live + 1

    npc:initNpcAi()
    npc:setLocalVar('xiLifePoint', startIdx)
    npc:setLocalVar('xiLifeSlot', startSlot)
    npc:setLocalVar('xiLife', 1)
    npc:setLocalVar('xiLifeJob', (character.job and jobIndex[character.job]) or 0)

    if startSlot > 0 then
        startPoint.taken[startSlot] = npc:getID()
    end

    if startPoint.kind ~= 'exit' then
        npc:lookAt(startPoint.x, startPoint.y, startPoint.z)
    end

    npc:timer(ARRIVAL_PAUSE_MS, function(n)
        walkToRandomPoint(n, zone, zoneId)
    end)
end

-- Top up to the zone's target rather than spawning a fixed number. Re-entering a zone whose
-- previous residents are still walking around would otherwise stack a whole fresh population on
-- top of them, and every round trip would add more.
local function topUpPopulation(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled then
        return
    end

    local wanted = state.population - state.live
    for i = 1, wanted do
        local player = anyPlayerIn(zone)
        if not player then
            break
        end

        player:timer((i - 1) * SPAWN_STAGGER_MS, function(_)
            spawnOne(zone, zoneId)
        end)
    end
end

local function despawnAll(zone, zoneId)
    local state = zoneState[zoneId]
    if not state then
        return
    end

    for _, npc in pairs(zone:getNPCs()) do
        if npc:getLocalVar('xiLife') == 1 then
            npc:setStatus(xi.status.DISAPPEAR)
        end
    end

    -- Hand every slot back. Wiping the population without this would leave every ring permanently
    -- full, and the next visit would find nowhere to stand anywhere in the zone.
    for _, point in ipairs(state.points or {}) do
        point.taken = {}
    end

    state.watch = {}
    state.live  = 0
end

-----------------------------------
-- Roadside encounters
--
-- Two PNPCs walking past each other stop, turn to face one another, stand there a few seconds and
-- then carry on. Nothing is said - the point is the body language.
--
-- Driven by a per-zone tick rather than anything per-NPC. The population caps at 22, so the worst
-- case is a couple of hundred distance checks every few seconds, and one timer per zone beats one
-- timer per PNPC. clearPath does not fire onPathComplete (CPathFind::Clear just empties the point
-- list), so stopping a PNPC this way has no effect on its lifecycle - it simply stands still until
-- the resume timer sends it on.
-----------------------------------

local scheduleEncounters

-- Only PNPCs actually on the move, and only those that have not already stopped once this trip.
local function travellingPNPCs(zone)
    local found = {}

    for _, npc in pairs(zone:getNPCs()) do
        local eligible =
            npc:getLocalVar('xiLife') == 1 and
            npc:getStatus() ~= xi.status.DISAPPEAR and
            npc:getLocalVar('xiLifeMet') == 0 and
            npc:isFollowingPath()

        if eligible then
            table.insert(found, npc)
        end
    end

    return found
end

-- Pick the journey back up where it was interrupted. The destination is recomputed from the point
-- and slot local vars rather than remembered, since local vars are integers and a position is not.
local function resumeTravel(npc, zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active then
        leave(npc, zone, zoneId)

        return
    end

    local point = state.points[npc:getLocalVar('xiLifePoint')]
    if not point then
        leave(npc, zone, zoneId)

        return
    end

    local x, y, z = destinationOf(point, npc:getLocalVar('xiLifeSlot'))
    local dx      = x - npc:getXPos()
    local dz      = z - npc:getZPos()

    -- Stopped near enough that PathTo would refuse the destination and strand them with no
    -- onPathComplete to ever move them on. Treat the stop as the arrival it effectively was.
    if ((dx * dx) + (dz * dz)) < (RESUME_MIN_DISTANCE * RESUME_MIN_DISTANCE) then
        arriveAt(npc, zone, zoneId)

        return
    end

    npc:pathTo(x, y, z, xi.path.flag.WALLHACK + xi.path.flag.SCRIPT)
end

local function startEncounter(zone, zoneId, one, two)
    -- Stop both before either turns, so each faces where the other actually came to rest.
    one:clearPath()
    two:clearPath()

    one:lookAt(two:getXPos(), two:getYPos(), two:getZPos())
    two:lookAt(one:getXPos(), one:getYPos(), one:getZPos())

    one:setLocalVar('xiLifeMet', 1)
    two:setLocalVar('xiLifeMet', 1)

    -- One duration for the pair, or one of them walks off mid-conversation.
    local duration = math.random(ENCOUNTER_MIN_MS, ENCOUNTER_MAX_MS)

    one:timer(duration, function(n)
        resumeTravel(n, zone, zoneId)
    end)

    two:timer(duration, function(n)
        resumeTravel(n, zone, zoneId)
    end)
end

-- Retire the slot that led them here before removing them. Re-routing instead would be gentler to
-- watch, but a PNPC stuck in scenery is often somewhere nothing can path out of, and it would just
-- stall again; despawning is the recovery that always works, and scheduleReplacement puts someone
-- fresh back into the zone. Standing perfectly still and then vanishing reads as a player logging
-- out, which is the least remarkable thing it could look like.
--
-- Blacklisting the slot is the part that matters. Without it the same unreachable spot would catch
-- the next PNPC to choose it, and the one after that.
local function rescueStuck(npc, zone, zoneId)
    local state   = zoneState[zoneId]
    local point   = state and state.points[npc:getLocalVar('xiLifePoint')]
    local slotIdx = npc:getLocalVar('xiLifeSlot')

    if point and slotIdx > 0 and point.slots[slotIdx] then
        point.slots[slotIdx].bad = true
        printf('[XI_LIFE] %s: slot %d at %s (%s) is unreachable, retired',
            zone:getName(), slotIdx, point.name, point.kind)
    end

    npc:clearPath()
    leave(npc, zone, zoneId)
end

-- Compares each travelling PNPC against where it stood last tick. Anyone stopped for an encounter
-- has had their path cleared, so isFollowingPath already excludes them and they cannot be mistaken
-- for stuck.
local function stuckTick(zone, zoneId)
    local state = zoneState[zoneId]
    if not state then
        return
    end

    local seen = {}

    for _, npc in pairs(zone:getNPCs()) do
        if npc:getLocalVar('xiLife') == 1 and npc:isFollowingPath() then
            local id    = npc:getID()
            local x     = npc:getXPos()
            local z     = npc:getZPos()
            local watch = state.watch[id]

            seen[id] = true

            local moved =
                not watch or
                math.abs(x - watch.x) >= STUCK_MOVE_EPSILON or
                math.abs(z - watch.z) >= STUCK_MOVE_EPSILON

            if moved then
                state.watch[id] = { x = x, z = z, strikes = 0 }
            else
                watch.strikes = watch.strikes + 1

                if watch.strikes >= STUCK_STRIKES then
                    state.watch[id] = nil
                    seen[id]        = nil
                    rescueStuck(npc, zone, zoneId)
                end
            end
        end
    end

    -- Forget anyone who has arrived, left, or stopped to talk, so ids cannot accumulate across a
    -- long session.
    for id in pairs(state.watch) do
        if not seen[id] then
            state.watch[id] = nil
        end
    end
end

local function encounterTick(zone, zoneId)
    local walkers = travellingPNPCs(zone)
    local paired  = {}

    for i = 1, #walkers - 1 do
        if not paired[i] then
            for j = i + 1, #walkers do
                local dx = walkers[i]:getXPos() - walkers[j]:getXPos()
                local dy = walkers[i]:getYPos() - walkers[j]:getYPos()
                local dz = walkers[i]:getZPos() - walkers[j]:getZPos()

                -- Height matters in a city built in layers. Two PNPCs on different tiers of Jeuno
                -- can be a few yalms apart on the map and nowhere near each other in the world.
                local flat  = (dx * dx) + (dz * dz)
                local close =
                    flat >= (ENCOUNTER_NEAR * ENCOUNTER_NEAR) and
                    flat <= (ENCOUNTER_FAR * ENCOUNTER_FAR) and
                    math.abs(dy) <= ENCOUNTER_HEIGHT

                if not paired[j] and close and math.random(100) <= ENCOUNTER_CHANCE then
                    paired[i] = true
                    paired[j] = true
                    startEncounter(zone, zoneId, walkers[i], walkers[j])

                    break
                end
            end
        end
    end
end

-- Same generation guard as the chatter loop below: the tick is anchored to a player's timers, so
-- it dies with them, and afterZoneIn restarts it unconditionally. Bumping the generation retires
-- whatever was still queued from a previous visit rather than letting two ticks run at once.
scheduleEncounters = function(zone, zoneId, generation)
    local state = zoneState[zoneId]
    if not state or not state.active then
        return
    end

    if generation == nil then
        state.encounterGeneration = (state.encounterGeneration or 0) + 1
        generation = state.encounterGeneration
    elseif generation ~= state.encounterGeneration then
        return
    end

    local player = anyPlayerIn(zone)
    if not player then
        return
    end

    player:timer(ENCOUNTER_TICK_MS, function(_)
        scheduleEncounters(zone, zoneId, generation)

        local ok, err = pcall(encounterTick, zone, zoneId)
        if not ok then
            printf('[XI_LIFE] encounter error in %s: %s', zone:getName(), tostring(err))
        end

        local movedOk, movedErr = pcall(stuckTick, zone, zoneId)
        if not movedOk then
            printf('[XI_LIFE] stuck check error in %s: %s', zone:getName(), tostring(movedErr))
        end
    end)
end

-----------------------------------
-- Chatter
-----------------------------------

-- Zone-wide lines, precomputed. Used when nobody is close enough to overhear a local remark.
local shoutLines = {}
for _, line in ipairs(xi.xiLife.chatter.lines) do
    if line.channel == 'shout' then
        table.insert(shoutLines, line)
    end
end

local function livingPNPCs(zone)
    local found = {}

    for _, npc in pairs(zone:getNPCs()) do
        if npc:getLocalVar('xiLife') == 1 and npc:getStatus() ~= xi.status.DISAPPEAR then
            table.insert(found, npc)
        end
    end

    return found
end

local function timeOfDayWord()
    local hour = VanadielHour()

    if hour < 6 then
        return 'the middle of the night'
    elseif hour < 12 then
        return 'morning'
    elseif hour < 17 then
        return 'afternoon'
    elseif hour < 20 then
        return 'evening'
    end

    return 'night'
end

-- Which pool each token draws from. {job2} exists so a line can name two different jobs.
local tokenPool =
{
    zone   = 'zone',
    job    = 'job',
    job2   = 'job',
    item   = 'item',
    price  = 'price',
    number = 'number',
}

local function tokenValue(token, speaker)
    if token == 'name' then
        return speaker.name
    end

    if token == 'time' then
        return timeOfDayWord()
    end

    -- A PNPC in full Artifact is visibly that job, so let it speak as one.
    if token == 'job' and speaker.job then
        return speaker.job
    end

    local pool = xi.xiLife.chatter.tokens[tokenPool[token] or '']
    if pool and #pool > 0 then
        return pool[math.random(#pool)]
    end

    return '{' .. token .. '}'
end

local function fillTokens(text, speaker)
    -- gsub with a function is called once per occurrence, so two {zone} tokens in one line get
    -- independent rolls rather than the same value twice.
    local filled = text:gsub('{(%w+)}', function(token)
        return tokenValue(token, speaker)
    end)

    return filled
end

local scheduleChatter

local function speakOnce(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active then
        return
    end

    local speakers = livingPNPCs(zone)
    if #speakers == 0 then
        return
    end

    local npc = speakers[math.random(#speakers)]

    -- Work out who could actually overhear this speaker before choosing what it says. Picking the
    -- line first wasted over half of every firing: 'say' lines only carry within SAY_RANGE, and in
    -- a capital the odds of a randomly chosen PNPC standing that close to the player are slim, so
    -- most ticks produced silence. With no one in earshot, only zone-wide lines are eligible.
    local audience = watchingPlayers(zone)
    local nearby   = {}
    for _, player in ipairs(audience) do
        local dx = player:getXPos() - npc:getXPos()
        local dz = player:getZPos() - npc:getZPos()

        if ((dx * dx) + (dz * dz)) <= (SAY_RANGE * SAY_RANGE) then
            table.insert(nearby, player)
        end
    end

    local pool = #nearby > 0 and xi.xiLife.chatter.lines or shoutLines
    if #pool == 0 then
        return
    end

    local line = pool[math.random(#pool)]

    -- The job is only known for PNPCs wearing a full Artifact set; the rest fall back to a random
    -- job in the line, which is fine since nobody can tell what a mixed-gear player is playing.
    local jobId   = npc:getLocalVar('xiLifeJob')
    local speaker =
    {
        name = npc:getName(),
        job  = jobId > 0 and xi.xiLife.chatter.tokens.job[jobId] or nil,
    }

    local text    = fillTokens(line.text, speaker)
    local isShout = line.channel == 'shout'
    local channel = isShout and xi.msg.channel.SHOUT or xi.msg.channel.SAY
    local heard   = isShout and audience or nearby

    for _, player in ipairs(heard) do
        player:printToPlayer(text, channel, speaker.name)
    end
end

-- Each zone's chatter loop carries a generation number. Restarting a zone bumps it, which
-- retires any chain still queued from a previous visit, so afterZoneIn can always start one
-- without risking two running at once.
--
-- Anchoring the loop to a player's action queue means it dies whenever that player's timers are
-- cleared, and the previous guard only started a chain on the transition into active - so once a
-- chain was lost the zone went permanently quiet. Restarting unconditionally fixes that.
scheduleChatter = function(zone, zoneId, generation)
    local state = zoneState[zoneId]
    if not state or not state.active then
        return
    end

    if generation == nil then
        state.chatterGeneration = (state.chatterGeneration or 0) + 1
        generation = state.chatterGeneration
    elseif generation ~= state.chatterGeneration then
        return
    end

    local player = anyPlayerIn(zone)
    if not player then
        return
    end

    local delay = math.random(CHATTER_MIN_DELAY_MS, CHATTER_MAX_DELAY_MS)

    player:timer(delay, function(_)
        -- Re-arm before speaking. If speakOnce throws, the chain has already been queued, so a
        -- single bad line cannot silence the zone for the rest of the session.
        scheduleChatter(zone, zoneId, generation)

        local ok, err = pcall(speakOnce, zone, zoneId)
        if not ok then
            printf('[XI_LIFE] chatter error in %s: %s', zone:getName(), tostring(err))
        end
    end)
end

-----------------------------------
-- Hooks
--
-- InteractionGlobal.afterZoneIn and onZoneOut are called from luautils for every zone, with the
-- zone's own handler passed in as fallbackFn. Call super first and hand its result straight back:
-- these return values are consumed upstream.
-----------------------------------

m:addOverride('InteractionGlobal.afterZoneIn', function(player, fallbackFn)
    local result = super(player, fallbackFn)

    local zone = player:getZone()
    if zone then
        local zoneId = zone:getID()
        local state  = prepareZone(zone, zoneId)

        if state.enabled and player:inMogHouse() then
            -- Walking into a Mog House arrives here, because it is a zone change back into the
            -- same zone. Tear the population down rather than topping it up: the player is still
            -- standing in the street server-side, so anything spawned would be pushed to their
            -- client and parade through the room.
            state.active = false
            despawnAll(zone, zoneId)
        elseif state.enabled then
            state.active = true
            topUpPopulation(zone, zoneId)

            -- Always restart. The generation counter retires whatever was queued before, so this
            -- cannot double the rate, and it recovers a chain that died with a player's timers.
            scheduleChatter(zone, zoneId)
            scheduleEncounters(zone, zoneId)
        end
    end

    return result
end)

m:addOverride('InteractionGlobal.onZoneOut', function(player, fallbackFn)
    local result = super(player, fallbackFn)

    local zone = player:getZone()
    if zone then
        local zoneId = zone:getID()
        local state  = zoneState[zoneId]

        -- Only tear down once the last player is gone. getPlayers still includes the player who is
        -- on their way out at this point, so one remaining means the zone is about to be empty.
        if state and state.enabled and #zone:getPlayers() <= 1 then
            state.active = false
            despawnAll(zone, zoneId)
        end
    end

    return result
end)

return m
