-----------------------------------
-- XI_LIFE: PlayerNPC city population
--
-- Populates every city zone a player walks into with dynamic NPCs that look and move like other
-- players: they arrive somewhere, loiter, walk on, and eventually leave through a zone line or a
-- home point crystal.
--
-- Hooks in through InteractionGlobal rather than per-zone scripts. luautils calls
-- InteractionGlobal.afterZoneIn and InteractionGlobal.onZoneOut unconditionally for every zone,
-- passing the zone's own handler in as a fallback, so overriding those two reaches all 250-odd
-- zones without editing a single Zone.lua.
--
-- Points of interest come from modules/custom/lua/xi_life_pois.lua, which is generated by
-- tools/xi_life/generate_pois.py out of npc_list, zonelines and the zone scripts.
-----------------------------------
require('modules/module_utils')
require('scripts/globals/interaction/interaction_global')
require('modules/custom/lua/xi_life_appearance')
require('modules/custom/lua/xi_life_pois')
require('modules/custom/lua/xi_life_chatter')

-- Hand-picked points added in game with !addnpcpoi. Optional: the file only exists once the
-- command has been used at least once, so this must not be a hard require. pcall rather than
-- utils.prequire, which lives in scripts/utils and may not be loaded this early.
pcall(require, 'modules/custom/lua/xi_life_custom_pois')
-----------------------------------
local m = Module:new('xi_life')

-----------------------------------
-- Tuning
-----------------------------------

-- How long a freshly spawned PNPC stands before setting off.
local ARRIVAL_PAUSE_MS = 8000

-- Loitering. Auction counters get longer: players genuinely stand at them a while, working the
-- menu and re-listing. Home points are a shorter pause for the ones who do not warp straight out.
local AUCTION_LOITER_MS   = 30000
local HOMEPOINT_LOITER_MS = 15000
local WANDER_LOITER_MS    = 15000

-- Chance a PNPC arriving at a home point warps out rather than loitering and moving on. Home
-- points are the only loiter point in the eleven city zones that have no auction house, so
-- treating them as purely terminal would leave those zones as silent thoroughfares.
local HOMEPOINT_DEPARTURE_CHANCE = 50

-- Gap between one PNPC leaving and its replacement arriving.
local RESPAWN_DELAY_MS = 3000

-- Stagger the initial fill so a city does not pop into existence all at once.
local SPAWN_STAGGER_MS = 1000

-- Chatter. The budget is per zone rather than per PNPC: twenty people each on their own timer is
-- a spam wall, and the rate would change every time the population did. One speaker is picked
-- from whoever is alive when the timer fires, so the pace stays constant in a hamlet or a capital.
local CHATTER_MIN_DELAY_MS = 10000
local CHATTER_MAX_DELAY_MS = 45000

-- 'say' lines are muttering, so they only carry if the speaker is close enough to overhear.
local SAY_RANGE = 20.0

-- Yalms of slop on x and z for every destination, so arrivals at a shared point do not stack.
-- y is left alone: nudging it risks putting someone through the floor or off a ledge.
local DEST_JITTER = 1.5

-- A zone needs somewhere to go and somewhere to leave from, or its PNPCs have nothing to do.
local MIN_POINTS      = 2
local MIN_EXIT_POINTS = 1

-- CPathFind::PathTo silently does nothing when the destination is within 1 yalm of where the
-- entity already stands (arePositionsClose in pathfind.cpp), which would leave a PNPC parked
-- forever with no onPathComplete to move it on. Keep destinations comfortably clear of that.
local MIN_TRAVEL_DISTANCE = 5.0

-- Kinds a PNPC stops travelling at. Everything else is somewhere it passes through.
local terminalKinds =
{
    exit      = true,
    homepoint = true,
}

-- Zones whose content may not be enabled on this server. Nothing else needs gating: the rest of
-- the generated zones are base game.
local zoneContentTag =
{
    [xi.zone.TAVNAZIAN_SAFEHOLD]     = 'COP',
    [xi.zone.AL_ZAHBI]               = 'TOAU',
    [xi.zone.AHT_URHGAN_WHITEGATE]   = 'TOAU',
    [xi.zone.SOUTHERN_SAN_DORIA_S]   = 'WOTG',
    [xi.zone.BASTOK_MARKETS_S]       = 'WOTG',
    [xi.zone.WINDURST_WATERS_S]      = 'WOTG',
    [xi.zone.WESTERN_ADOULIN]        = 'SOA',
    [xi.zone.EASTERN_ADOULIN]        = 'SOA',
}

-----------------------------------
-- State
--
-- One entry per zone we have looked at. `points` is the navmesh-validated subset of the generated
-- data, `live` counts PNPCs currently walking around, and `active` says whether a player is here
-- to see them.
-----------------------------------

local zoneState = {}

-- Local vars are integers, so a PNPC's job is stored as its index into the chatter job list.
local jobIndex = {}
for index, job in ipairs(xi.xiLife.chatter.tokens.job) do
    jobIndex[job] = index
end

local function jitter(value)
    return value + ((math.random() * 2) - 1) * DEST_JITTER
end

local function anyPlayerIn(zone)
    for _, player in pairs(zone:getPlayers()) do
        return player
    end

    return nil
end

-----------------------------------
-- Zone preparation
--
-- Run once per zone, the first time a player arrives. The generator cannot consult the navmesh -
-- it lives in this process, not in Python - so the points it produces are candidates, and this is
-- where the unreachable ones are dropped. A PNPC sent to an off-mesh point would stall short of
-- it, never arriving and so never despawning.
-----------------------------------

local function prepareZone(zone, zoneId)
    if zoneState[zoneId] then
        return zoneState[zoneId]
    end

    local data = xi.xiLife.pois[zoneId]
    if not data then
        zoneState[zoneId] = { enabled = false }

        return zoneState[zoneId]
    end

    local contentTag = zoneContentTag[zoneId]
    if contentTag and not xi.module.isContentEnabled(contentTag) then
        zoneState[zoneId] = { enabled = false }

        return zoneState[zoneId]
    end

    local candidates = {}
    for _, point in ipairs(data.points) do
        table.insert(candidates, point)
    end

    -- Points added in game with !addnpcpoi, layered on top of the generated set. They survive
    -- regeneration because they live in their own file.
    local custom = xi.xiLife.customPois and xi.xiLife.customPois[zoneId]
    if custom then
        for _, point in ipairs(custom) do
            table.insert(candidates, point)
        end
    end

    local points   = {}
    local rejected = 0

    for _, point in ipairs(candidates) do
        -- Zone lines are never culled. They are the only way out of a zone, and losing them
        -- strands the whole population. They also do not need the mesh: PathTo is called with
        -- WALLHACK, which routes through CPathFind::FindClosestPath, and that appends the exact
        -- destination to the path regardless of what the navmesh says. The NPC walks the mesh as
        -- far as it goes and then moves directly to the point, so arrival still happens.
        local keep =
            point.kind == 'exit' or
            zone:isNavigablePoint({ x = point.x, y = point.y, z = point.z })

        if keep then
            table.insert(points, point)
        else
            rejected = rejected + 1
            printf('[XI_LIFE] %s: point off the navmesh, dropped: %s (%s)',
                zone:getName(), point.name, point.kind)
        end
    end

    local exits = 0
    for _, point in ipairs(points) do
        if terminalKinds[point.kind] then
            exits = exits + 1
        end
    end

    local enabled = #points >= MIN_POINTS and exits >= MIN_EXIT_POINTS

    zoneState[zoneId] =
    {
        enabled    = enabled,
        points     = points,
        population = data.population,
        live       = 0,
        active     = false,
    }

    if enabled then
        printf('[XI_LIFE] %s: %d points (%d dropped), population %d',
            zone:getName(), #points, rejected, data.population)
    else
        printf('[XI_LIFE] %s: disabled, only %d usable points and %d ways to leave',
            zone:getName(), #points, exits)
    end

    return zoneState[zoneId]
end

-----------------------------------
-- PlayerNPC lifecycle
-----------------------------------

local spawnOne
local walkToRandomPoint
local leave

-- Sends the PNPC somewhere it is not already standing, and remembers which point it chose so
-- onPathComplete knows what kind of place it just arrived at.
--
-- Two candidates are refused. Walking from one auction counter to another looks absurd - the
-- counters share a room, so it reads as pacing rather than travelling. And anything within
-- MIN_TRAVEL_DISTANCE would leave the NPC stranded, since PathTo ignores destinations that close.
-- If nothing at all qualifies the PNPC leaves rather than standing there indefinitely, since
-- without a path there is no onPathComplete to ever move it on again.
walkToRandomPoint = function(npc, zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled then
        return
    end

    if not state.active then
        leave(npc, zone, zoneId)

        return
    end

    local currentIdx   = npc:getLocalVar('xiLifePoint')
    local currentPoint = state.points[currentIdx]
    local atAuction    = currentPoint and currentPoint.kind == 'auction'

    local preferred = {}
    local fallback  = {}

    for idx, point in ipairs(state.points) do
        if idx ~= currentIdx then
            local dx        = point.x - npc:getXPos()
            local dz        = point.z - npc:getZPos()
            local farEnough = ((dx * dx) + (dz * dz)) > (MIN_TRAVEL_DISTANCE * MIN_TRAVEL_DISTANCE)

            if farEnough then
                if atAuction and point.kind == 'auction' then
                    table.insert(fallback, idx)
                else
                    table.insert(preferred, idx)
                end
            end
        end
    end

    local choices = #preferred > 0 and preferred or fallback
    if #choices == 0 then
        leave(npc, zone, zoneId)

        return
    end

    local destIdx     = choices[math.random(#choices)]
    local destination = state.points[destIdx]

    npc:setLocalVar('xiLifePoint', destIdx)
    npc:pathTo(
        jitter(destination.x), destination.y, jitter(destination.z),
        xi.path.flag.WALLHACK + xi.path.flag.SCRIPT
    )
end

local function scheduleReplacement(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active or state.live >= state.population then
        return
    end

    local player = anyPlayerIn(zone)
    if not player then
        return
    end

    player:timer(RESPAWN_DELAY_MS, function(_)
        spawnOne(zone, zoneId)
    end)
end

leave = function(npc, zone, zoneId)
    local state = zoneState[zoneId]

    npc:setStatus(xi.status.DISAPPEAR)

    if state then
        state.live = math.max(0, state.live - 1)
    end

    scheduleReplacement(zone, zoneId)
end

spawnOne = function(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled or not state.active then
        return
    end

    if state.live >= state.population then
        return
    end

    local startIdx   = math.random(#state.points)
    local startPoint = state.points[startIdx]
    local character  = xi.xiLife.appearance.randomCharacter()

    local npc = zone:insertDynamicEntity(
    {
        objtype  = xi.objType.NPC,
        name     = character.name,
        look     = character.look,
        x        = jitter(startPoint.x),
        y        = startPoint.y,
        z        = jitter(startPoint.z),
        rotation = math.random(0, 255),

        -- namevis 0, not VIS_ICON: the (I) icon marks a talkable NPC and gives the game away.
        namevis  = 0,
        releaseIdOnDisappear = true,

        onPathComplete = function(pnpc)
            local currentState = zoneState[zoneId]
            if not currentState or not currentState.active then
                leave(pnpc, zone, zoneId)

                return
            end

            local arrived = currentState.points[pnpc:getLocalVar('xiLifePoint')]
            local kind    = arrived and arrived.kind or 'exit'

            if kind == 'auction' then
                pnpc:timer(AUCTION_LOITER_MS, function(n)
                    walkToRandomPoint(n, zone, zoneId)
                end)

                return
            end

            -- Points added in game with !addnpcpoi. Somewhere to stand, never a way out.
            if kind == 'wander' then
                pnpc:timer(WANDER_LOITER_MS, function(n)
                    walkToRandomPoint(n, zone, zoneId)
                end)

                return
            end

            -- Home points are both a place to stand and a way out, so roll for which this is.
            if kind == 'homepoint' and math.random(100) > HOMEPOINT_DEPARTURE_CHANCE then
                pnpc:timer(HOMEPOINT_LOITER_MS, function(n)
                    walkToRandomPoint(n, zone, zoneId)
                end)

                return
            end

            leave(pnpc, zone, zoneId)
        end,
    })

    if not npc then
        return
    end

    state.live = state.live + 1

    npc:initNpcAi()
    npc:setLocalVar('xiLifePoint', startIdx)
    npc:setLocalVar('xiLife', 1)
    npc:setLocalVar('xiLifeJob', (character.job and jobIndex[character.job]) or 0)
    npc:timer(ARRIVAL_PAUSE_MS, function(n)
        walkToRandomPoint(n, zone, zoneId)
    end)
end

-- Top up to the zone's target rather than spawning a fixed number. Re-entering a zone whose
-- previous residents are still walking around would otherwise stack a whole fresh population on
-- top of them, and every round trip would add more.
local function topUpPopulation(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.enabled then
        return
    end

    local wanted = state.population - state.live
    for i = 1, wanted do
        local player = anyPlayerIn(zone)
        if not player then
            break
        end

        player:timer((i - 1) * SPAWN_STAGGER_MS, function(_)
            spawnOne(zone, zoneId)
        end)
    end
end

local function despawnAll(zone, zoneId)
    local state = zoneState[zoneId]
    if not state then
        return
    end

    for _, npc in pairs(zone:getNPCs()) do
        if npc:getLocalVar('xiLife') == 1 then
            npc:setStatus(xi.status.DISAPPEAR)
        end
    end

    state.live = 0
end

-----------------------------------
-- Chatter
-----------------------------------

local function livingPNPCs(zone)
    local found = {}

    for _, npc in pairs(zone:getNPCs()) do
        if npc:getLocalVar('xiLife') == 1 and npc:getStatus() ~= xi.status.DISAPPEAR then
            table.insert(found, npc)
        end
    end

    return found
end

local function timeOfDayWord()
    local hour = VanadielHour()

    if hour < 6 then
        return 'the middle of the night'
    elseif hour < 12 then
        return 'morning'
    elseif hour < 17 then
        return 'afternoon'
    elseif hour < 20 then
        return 'evening'
    end

    return 'night'
end

-- Which pool each token draws from. {job2} exists so a line can name two different jobs.
local tokenPool =
{
    zone   = 'zone',
    job    = 'job',
    job2   = 'job',
    item   = 'item',
    price  = 'price',
    number = 'number',
}

local function tokenValue(token, speaker)
    if token == 'name' then
        return speaker.name
    end

    if token == 'time' then
        return timeOfDayWord()
    end

    -- A PNPC in full Artifact is visibly that job, so let it speak as one.
    if token == 'job' and speaker.job then
        return speaker.job
    end

    local pool = xi.xiLife.chatter.tokens[tokenPool[token] or '']
    if pool and #pool > 0 then
        return pool[math.random(#pool)]
    end

    return '{' .. token .. '}'
end

local function fillTokens(text, speaker)
    -- gsub with a function is called once per occurrence, so two {zone} tokens in one line get
    -- independent rolls rather than the same value twice.
    local filled = text:gsub('{(%w+)}', function(token)
        return tokenValue(token, speaker)
    end)

    return filled
end

local scheduleChatter

local function speakOnce(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active then
        return
    end

    local speakers = livingPNPCs(zone)
    if #speakers == 0 then
        return
    end

    local npc  = speakers[math.random(#speakers)]
    local line = xi.xiLife.chatter.lines[math.random(#xi.xiLife.chatter.lines)]

    -- The job is only known for PNPCs wearing a full Artifact set; the rest fall back to a random
    -- job in the line, which is fine since nobody can tell what a mixed-gear player is playing.
    local jobId   = npc:getLocalVar('xiLifeJob')
    local speaker =
    {
        name = npc:getName(),
        job  = jobId > 0 and xi.xiLife.chatter.tokens.job[jobId] or nil,
    }

    local text      = fillTokens(line.text, speaker)
    local isShout   = line.channel == 'shout'
    local channel   = isShout and xi.msg.channel.SHOUT or xi.msg.channel.SAY

    for _, player in pairs(zone:getPlayers()) do
        local heard = isShout

        if not heard then
            local dx = player:getXPos() - npc:getXPos()
            local dz = player:getZPos() - npc:getZPos()
            heard = ((dx * dx) + (dz * dz)) <= (SAY_RANGE * SAY_RANGE)
        end

        if heard then
            player:printToPlayer(text, channel, speaker.name)
        end
    end
end

scheduleChatter = function(zone, zoneId)
    local state = zoneState[zoneId]
    if not state or not state.active then
        return
    end

    local player = anyPlayerIn(zone)
    if not player then
        return
    end

    local delay = math.random(CHATTER_MIN_DELAY_MS, CHATTER_MAX_DELAY_MS)

    player:timer(delay, function(_)
        speakOnce(zone, zoneId)
        scheduleChatter(zone, zoneId)
    end)
end

-----------------------------------
-- Hooks
--
-- InteractionGlobal.afterZoneIn and onZoneOut are called from luautils for every zone, with the
-- zone's own handler passed in as fallbackFn. Call super first and hand its result straight back:
-- these return values are consumed upstream.
-----------------------------------

m:addOverride('InteractionGlobal.afterZoneIn', function(player, fallbackFn)
    local result = super(player, fallbackFn)

    local zone = player:getZone()
    if zone then
        local zoneId = zone:getID()
        local state  = prepareZone(zone, zoneId)

        if state.enabled then
            local wasActive = state.active

            state.active = true
            topUpPopulation(zone, zoneId)

            -- Only start the loop on the transition into active, or a second player arriving
            -- would leave two chains running and double the chatter rate.
            if not wasActive then
                scheduleChatter(zone, zoneId)
            end
        end
    end

    return result
end)

m:addOverride('InteractionGlobal.onZoneOut', function(player, fallbackFn)
    local result = super(player, fallbackFn)

    local zone = player:getZone()
    if zone then
        local zoneId = zone:getID()
        local state  = zoneState[zoneId]

        -- Only tear down once the last player is gone. getPlayers still includes the player who is
        -- on their way out at this point, so one remaining means the zone is about to be empty.
        if state and state.enabled and #zone:getPlayers() <= 1 then
            state.active = false
            despawnAll(zone, zoneId)
        end
    end

    return result
end)

return m
